// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WindmillUIClient is the client API for WindmillUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WindmillUIClient interface {
	// ListWindmillSpecs returns a list of Windmill(s) that can be started through the UI.
	ListWindmillSpecs(ctx context.Context, in *ListWindmillSpecsRequest, opts ...grpc.CallOption) (WindmillUI_ListWindmillSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type windmillUIClient struct {
	cc grpc.ClientConnInterface
}

func NewWindmillUIClient(cc grpc.ClientConnInterface) WindmillUIClient {
	return &windmillUIClient{cc}
}

func (c *windmillUIClient) ListWindmillSpecs(ctx context.Context, in *ListWindmillSpecsRequest, opts ...grpc.CallOption) (WindmillUI_ListWindmillSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &WindmillUI_ServiceDesc.Streams[0], "/v1.WindmillUI/ListWindmillSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &windmillUIListWindmillSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WindmillUI_ListWindmillSpecsClient interface {
	Recv() (*ListWindmillSpecsResponse, error)
	grpc.ClientStream
}

type windmillUIListWindmillSpecsClient struct {
	grpc.ClientStream
}

func (x *windmillUIListWindmillSpecsClient) Recv() (*ListWindmillSpecsResponse, error) {
	m := new(ListWindmillSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *windmillUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.WindmillUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WindmillUIServer is the server API for WindmillUI service.
// All implementations must embed UnimplementedWindmillUIServer
// for forward compatibility
type WindmillUIServer interface {
	// ListWindmillSpecs returns a list of Windmill(s) that can be started through the UI.
	ListWindmillSpecs(*ListWindmillSpecsRequest, WindmillUI_ListWindmillSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedWindmillUIServer()
}

// UnimplementedWindmillUIServer must be embedded to have forward compatible implementations.
type UnimplementedWindmillUIServer struct {
}

func (UnimplementedWindmillUIServer) ListWindmillSpecs(*ListWindmillSpecsRequest, WindmillUI_ListWindmillSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListWindmillSpecs not implemented")
}
func (UnimplementedWindmillUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedWindmillUIServer) mustEmbedUnimplementedWindmillUIServer() {}

// UnsafeWindmillUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WindmillUIServer will
// result in compilation errors.
type UnsafeWindmillUIServer interface {
	mustEmbedUnimplementedWindmillUIServer()
}

func RegisterWindmillUIServer(s grpc.ServiceRegistrar, srv WindmillUIServer) {
	s.RegisterService(&WindmillUI_ServiceDesc, srv)
}

func _WindmillUI_ListWindmillSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListWindmillSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WindmillUIServer).ListWindmillSpecs(m, &windmillUIListWindmillSpecsServer{stream})
}

type WindmillUI_ListWindmillSpecsServer interface {
	Send(*ListWindmillSpecsResponse) error
	grpc.ServerStream
}

type windmillUIListWindmillSpecsServer struct {
	grpc.ServerStream
}

func (x *windmillUIListWindmillSpecsServer) Send(m *ListWindmillSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _WindmillUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindmillUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.WindmillUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindmillUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WindmillUI_ServiceDesc is the grpc.ServiceDesc for WindmillUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WindmillUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.WindmillUI",
	HandlerType: (*WindmillUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _WindmillUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListWindmillSpecs",
			Handler:       _WindmillUI_ListWindmillSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "windmill-ui.proto",
}
